### ISSUE TITLE
readsb

### ISSUE THREAD

**Issue by sledzik1984** [claws/dump1090-exporter#33]
Runs without any problems with readsb (on same computer). You could metion that in readme.

**Comment by claws** [comment]
Hmm, I haven't heard of ``reasdsb`` before. When I search for it I find quite a few versions. I'm confused as to which one I would say it works with. When you say it works with readsb, is that:

- the [readsb archived fork](https://github.com/Mictronics/readsb) of ``dump1090-fa``?
- the newer protobuf based version of [readsb](https://github.com/Mictronics/readsb-protobuf)? I'm guessing its not the protobuf version because it says it is not compatible with tools that expect JSON data. 
- Perhaps it could even be this [fork](https://github.com/wiedehopf/readsb) of the archived readsb repo?

**Comment by sledzik1984** [comment]
I am using that one - it is under active development (from time to time)
https://github.com/wiedehopf/readsb

**Comment by gaskippy** [comment]
I am using dump1090-exporter with readsb.  Everything is graphing in Grafana except signal.  When running dump1090-exporter in debug mode, i see it cannot find a json file called "local".  

Thank you in advance, great work!
